### ISSUE TITLE
What is the reason behind the size?

### ISSUE THREAD

**Issue by niccokunzmann** [the-shroom/the-shroom#2]
Why do you use this size of the box? Can it be smaller or will the mushrooms hit the wall then?
Can it be bigger or will the moisturizing not work then?

**Comment by marcoka2000** [comment]
Size doesn’t matter that much.
We orientated ourself on those standard size bags which are normally used for fruit growing but there would fit three to four of them into the box.

Theoretically it’s scalable however you want, you only should also scale the moisturiser.

The goal is to achieve a humidity between 85% – 92%.
We used a standard 12V fogger (from a table fountain) in our hackathon project and were able to achieve a humidity of about 80% within minutes but didn’t see it increasing much during the next two hours we were presenting it - so that’s probably one of the first things we have to look into for enhancements.

**Comment by niccokunzmann** [comment]
I am asking because I would think about something one can hang at the wall.
Thanks!
